version: '2.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d # configure schema
    environment:
      MYSQL_ROOT_PASSWORD: YOUR_DB_PASSWORD # REPLACE
      MYSQL_DATABASE: YOUR_DB_USERNAME # REPLACE
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  rosie:
    image: rosiebot
    depends_on:
      db:
        condition: service_healthy